export const GETRECIPELOADING= 'GETRECIPELOADING';
export const GETRECIPESUCSESS ='GETREIPESUCSESS';
export const GETRECIPEFALE='GETRECIPEFALE'; 
export const GETRECIPELOADINGONE= 'GETRECIPELOADINGONE';
export const GETRECIPESUCSESSONE ='GETREIPESUCSESSONE';
export const GETRECIPEFALEONE='GETRECIPEFALEONE'; 